import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { db, now } from '../lib/db';
import { clientDeadlinesBetween, dateOnly, localDate } from '../lib/logic';
import { fmtDate, inputDate } from '../lib/ui';
import { queueSync } from '../services/sync';
import { Card, Chip } from '../components/UI';
import { EventForm } from '../components/Forms';
import type { CalendarEvent } from '../types/models';

export function CalendarPage(){
 const events=useLiveQuery(()=>db.events.toArray(),[])||[];const tasks=useLiveQuery(()=>db.tasks.toArray(),[])||[];const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const settings=useLiveQuery(()=>db.settings.get('settings'),[]);
 const [filter,setFilter]=useState<'Tutto'|'Lavoro'|'Personale'>('Tutto');const [view,setView]=useState<'Giorno'|'Settimana'|'Mese'>(settings?.calendarView||'Mese');const [cursor,setCursor]=useState(new Date());const [edit,setEdit]=useState<CalendarEvent|null>(null);
 const monthStart=new Date(cursor.getFullYear(),cursor.getMonth(),1);const gridStart=new Date(monthStart);gridStart.setDate(gridStart.getDate()-((gridStart.getDay()+6)%7));const gridDays=Array.from({length:42},(_,i)=>{const d=new Date(gridStart);d.setDate(d.getDate()+i);return d});const gridEnd=gridDays[41];
 const virtualDeadlines=clients.flatMap(c=>clientDeadlinesBetween(c,gridStart,gridEnd).map(d=>({id:`deadline-${c.id}-${dateOnly(d)}`,title:`Scadenza ${c.name}`,kind:'Lavoro' as const,category:'Scadenza cliente',startAt:dateOnly(d),allDay:true,createdAt:'',updatedAt:'',clientId:c.id} as CalendarEvent)));const allEvents=[...events.filter(e=>!e.deletedAt),...virtualDeadlines];
 const move=(n:number)=>{const d=new Date(cursor);if(view==='Mese')d.setMonth(d.getMonth()+n);else d.setDate(d.getDate()+n*(view==='Settimana'?7:1));setCursor(d)};
 const listFor=(start:Date,end:Date)=>allEvents.filter(e=>{const d=localDate(e.startAt);return d>=start&&d<=end&&(filter==='Tutto'||e.kind===filter)}).sort((a,b)=>+localDate(a.startAt)-+localDate(b.startAt));
 const dayStart=new Date(cursor.getFullYear(),cursor.getMonth(),cursor.getDate());const dayEnd=new Date(dayStart);dayEnd.setHours(23,59,59,999);const weekStart=new Date(dayStart);weekStart.setDate(weekStart.getDate()-((weekStart.getDay()+6)%7));const weekEnd=new Date(weekStart);weekEnd.setDate(weekEnd.getDate()+6);weekEnd.setHours(23,59,59,999);const visibleList=view==='Giorno'?listFor(dayStart,dayEnd):listFor(weekStart,weekEnd);
 return <main className="page calendar-page"><header className="page-title"><div><h1>Calendario</h1><p>Lavoro e personale, senza sovrapposizioni.</p></div></header>
 <div className="calendar-toolbar"><div className="chips">{(['Giorno','Settimana','Mese'] as const).map(x=><Chip active={view===x} onClick={()=>{setView(x);db.settings.update('settings',{calendarView:x,updatedAt:now()});queueSync()}} key={x}>{x}</Chip>)}</div><div className="calendar-nav"><button onClick={()=>move(-1)}><ChevronLeft/></button><strong>{view==='Mese'?fmtDate(cursor,{month:'long',year:'numeric'}):fmtDate(cursor,{day:'numeric',month:'long',year:'numeric'})}</strong><button onClick={()=>move(1)}><ChevronRight/></button></div><div className="chips">{(['Tutto','Lavoro','Personale'] as const).map(x=><Chip active={filter===x} onClick={()=>setFilter(x)} key={x}>{x}</Chip>)}</div></div>
 {view==='Mese'?<div className="month-calendar"><div className="weekday-head">{['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{gridDays.map(d=>{const key=dateOnly(d);const items=allEvents.filter(e=>dateOnly(e.startAt)===key&&(filter==='Tutto'||e.kind===filter));const taskItems=tasks.filter(t=>!t.deletedAt&&t.dueAt&&dateOnly(t.dueAt)===key);return <div className={`day-cell ${d.getMonth()!==cursor.getMonth()?'outside':''} ${key===inputDate()?'today':''}`} key={key}><button className="day-number" onClick={()=>{setCursor(d);setView('Giorno')}}>{d.getDate()}</button><div className="cell-items">{items.slice(0,4).map(e=><button key={e.id} className={`event-pill ${e.kind.toLowerCase()}`} onClick={()=>!e.id.startsWith('deadline-')&&setEdit(e)}>{e.allDay?'':new Date(e.startAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})+' '}{e.title}</button>)}{taskItems.slice(0,2).map(t=><span className="event-pill task" key={t.id}>☑ {t.title}</span>)}{items.length+taskItems.length>6&&<small>+{items.length+taskItems.length-6} altri</small>}</div></div>})}</div></div>:<div className="calendar-list big">{visibleList.map(e=><Card key={e.id} className={e.kind==='Personale'?'personal':''}><div className="time">{fmtDate(e.startAt,{weekday:'short',day:'numeric'})}<strong>{e.allDay?'—':new Date(e.startAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</strong></div><button className="event-main" onClick={()=>!e.id.startsWith('deadline-')&&setEdit(e)}><h3>{e.title}</h3><p>{e.kind} · {e.category}</p></button></Card>)}</div>}
 {edit&&<EventForm kind={edit.kind} initial={edit} close={()=>setEdit(null)}/>}</main>;
}
