import { Link, useParams } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { useState } from 'react';
import { db, now } from '../lib/db';
import { clientHealth, daysUntil, nextClientDeadline, paymentStatus } from '../lib/logic';
import { fmtDate, WORKFLOW } from '../lib/ui';
import { queueSync } from '../services/sync';
import { buildStrategy } from '../services/strategy';
import { Card, Chip, Empty, PrimaryButton } from '../components/UI';
import { ScriptForm, TaskForm } from '../components/Forms';
import { downloadText, scriptText } from '../lib/exportScript';
import type { WorkflowStage } from '../types/models';

export function Clients(){
 const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const payments=useLiveQuery(()=>db.payments.toArray(),[])||[];const scripts=useLiveQuery(()=>db.scripts.toArray(),[])||[];const active=clients.filter(c=>!c.deletedAt);
 return <main className="page"><header className="page-title"><div><h1>Clienti attivi</h1><p>Tutto ciò che richiede attenzione, senza rumore.</p></div></header><div className="client-grid">{active.map(c=>{const h=clientHealth(c,payments,scripts);const deadline=nextClientDeadline(c);return <Link className="client-card" to={`/clienti/${c.id}`} key={c.id}><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><div className="client-main"><div className="row spread"><h3>{c.name}</h3><span className={`status ${h.state.toLowerCase()}`}>{h.state}</span></div><p>{c.niche} · {c.platforms.join(' + ')||'—'}</p><div className="mini-grid"><span><b>{c.contentTarget}</b><small>contenuti/mese</small></span><span><b>€ {c.monthlyFee}</b><small>/mese</small></span></div>{deadline&&<div className="deadline-pill">Prossima scadenza {fmtDate(deadline)} · {daysUntil(deadline)} gg</div>}<div className="next-action">⚡ {h.reason}</div></div></Link>})}</div>{!active.length&&<Empty title="Nessun cliente ancora"/>}</main>;
}

export function ClientPage(){
 const {id}=useParams();const client=useLiveQuery(()=>id?db.clients.get(id):undefined,[id]);const scripts=useLiveQuery(()=>id?db.scripts.where('clientId').equals(id).toArray():[],[id])||[];const ideas=useLiveQuery(()=>id?db.ideas.where('clientId').equals(id).toArray():[],[id])||[];const payments=useLiveQuery(()=>id?db.payments.where('clientId').equals(id).toArray():[],[id])||[];const strategies=useLiveQuery(()=>id?db.strategies.where('clientId').equals(id).toArray():[],[id])||[];const tasks=useLiveQuery(()=>id?db.tasks.where('clientId').equals(id).toArray():[],[id])||[];
 const [tab,setTab]=useState<'overview'|'scripts'|'strategy'|'more'>('overview');const [newScript,setNewScript]=useState(false);const [stage,setStage]=useState<WorkflowStage|null>(null);
 if(!client)return <main className="page"><p>Caricamento…</p></main>;
 const h=clientHealth(client,payments,scripts);const ready=scripts.filter(s=>s.status==='Pronto'&&!s.deletedAt).length;const deadline=nextClientDeadline(client);const createStrategy=async()=>{const s=buildStrategy(client);await db.strategies.put(s);queueSync();setTab('strategy')};
 return <main className="page client-detail"><Link to="/clienti" className="back">← Clienti</Link><Card className="client-hero"><div><span className="eyebrow">{client.niche}</span><h1>{client.name}</h1><p>{client.platforms.join(' + ')||'Nessuna piattaforma'} · € {client.monthlyFee}/mese</p>{deadline&&<p className="deadline-main">Ciclo attuale fino al <strong>{fmtDate(deadline,{day:'numeric',month:'long',year:'numeric'})}</strong></p>}</div><div className="client-score"><span className={`status ${h.state.toLowerCase()}`}>{h.state}</span><strong>{ready}/{client.contentTarget}</strong><small>script pronti</small></div></Card>
 <Card className="next-client"><span className="eyebrow">⚡ PROSSIMA AZIONE</span><h2>{ready<client.contentTarget?`Completa ${Math.max(0,client.contentTarget-ready)} script prima della prossima registrazione`:'Workflow pronto per la fase successiva'}</h2></Card>
 <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Panoramica</button><button className={tab==='scripts'?'active':''} onClick={()=>setTab('scripts')}>Script</button><button className={tab==='strategy'?'active':''} onClick={()=>setTab('strategy')}>Strategia</button><button className={tab==='more'?'active':''} onClick={()=>setTab('more')}>Altro</button></div>
 {tab==='overview'&&<><Card className="workflow-card"><div className="section-head compact"><div><h2>Workflow operativo</h2><p>Crea, completa e controlla le fasi del cliente.</p></div></div><div className="workflow operational">{WORKFLOW.map(st=>{const stTasks=tasks.filter(t=>t.stage===st&&!t.deletedAt);const open=stTasks.filter(t=>!t.completed);return <div key={st} className={open.length?'workflow-step has-open':'workflow-step'}><b>{st}</b><span>{open.length?`${open.length} da fare`:stTasks.length?'Completato':'Da pianificare'}</span><button onClick={()=>setStage(st)}>+ attività</button></div>})}</div><div className="workflow-tasks">{tasks.filter(t=>!t.deletedAt).map(t=><div className="agenda-row" key={t.id}><div><strong>{t.title}</strong><span>{t.stage||'Task'}{t.dueAt?` · ${fmtDate(t.dueAt)}`:''}</span></div><button className={t.completed?'done-check':'task-check'} onClick={()=>{db.tasks.update(t.id,{completed:!t.completed,updatedAt:now()});queueSync()}}>{t.completed?'✓':'○'}</button></div>)}</div></Card><div className="bento"><Card><span className="eyebrow">💡 IDEE</span><h3>{ideas.filter(i=>!i.deletedAt).length}</h3><p>salvate</p></Card><Card><span className="eyebrow">📝 SCRIPT</span><h3>{ready}/{scripts.filter(s=>!s.deletedAt).length||client.contentTarget}</h3><p>pronti</p></Card><Card><span className="eyebrow">💰 PAGAMENTO</span><h3>{payments.some(p=>paymentStatus(p)==='Scaduto'&&!p.deletedAt)?'Scaduto':'Regolare'}</h3></Card></div>{stage&&<TaskForm clientId={client.id} defaultStage={stage} close={()=>setStage(null)}/>}</>}
 {tab==='scripts'&&<><div className="section-head"><div><h2>Script</h2><p>Idea → Script → Registrazione</p></div><PrimaryButton onClick={()=>setNewScript(true)}>+ Nuovo script</PrimaryButton></div><div className="list">{scripts.filter(s=>!s.deletedAt).map(s=><Card key={s.id}><div className="row spread"><div><h3>{s.title}</h3><p>{s.platform} · {s.format} · {s.status}</p></div><div className="row"><button className="btn ghost" onClick={()=>navigator.clipboard.writeText(scriptText(s))}>Copia</button><button className="btn ghost" onClick={()=>downloadText(`${s.title}.txt`,scriptText(s))}>Esporta</button></div></div>{s.referenceUrls.length>0&&<div className="refs">{s.referenceUrls.map((r,i)=><a href={r.url} target="_blank" rel="noreferrer" key={i}>🔗 {r.note||'Riferimento'}</a>)}</div>}</Card>)}</div>{newScript&&<ScriptForm client={client} ideas={ideas} close={()=>setNewScript(false)}/>}</>}
 {tab==='strategy'&&<><div className="section-head"><div><h2>Strategia</h2><p>Generazione deterministica, senza API obbligatorie.</p></div><PrimaryButton onClick={createStrategy}>Crea strategia</PrimaryButton></div>{strategies.length?strategies.slice().reverse().map(s=><Card key={s.id}><h3>{s.objective}</h3><p>{s.summary}</p><div className="chips">{s.pillars.map(p=><Chip key={p.name}>{p.name} · {p.count}</Chip>)}</div><div className="strategy-ideas">{s.ideas.map((i,idx)=><div key={idx}><b>{idx+1}. {i.title}</b><span>{i.pillar} · {i.funnel}</span><small>{i.hook}</small></div>)}</div></Card>):<Empty title="Nessuna strategia ancora" action={<PrimaryButton onClick={createStrategy}>Crea strategia</PrimaryButton>}/>}</>}
 {tab==='more'&&<div className="bento"><Card><span className="eyebrow">TONO</span><h3>{client.tone||'Non impostato'}</h3></Card><Card><span className="eyebrow">DA EVITARE</span><p>{client.avoid?.join(', ')||'Nessuna regola'}</p></Card><Card><span className="eyebrow">META ADS</span><h3>{client.metaAds?'Sì':'No'}</h3></Card></div>}
 </main>;
}
