import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db, now } from '../lib/db';
import { localDate, paymentStatus } from '../lib/logic';
import { fmtDate } from '../lib/ui';
import { queueSync } from '../services/sync';
import { Card, Chip, PrimaryButton } from '../components/UI';
import { PaymentForm } from '../components/Forms';

export function PaymentsPage(){
 const payments=useLiveQuery(()=>db.payments.toArray(),[])||[];const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const [months,setMonths]=useState<1|3|6|12>(3);const [add,setAdd]=useState(false);
 const active=payments.filter(p=>!p.deletedAt);const paid=active.filter(p=>p.paidAt);const pending=active.filter(p=>!p.paidAt);const totalPaid=paid.reduce((s,p)=>s+p.amount,0);const totalPending=pending.reduce((s,p)=>s+p.amount,0);const nowD=new Date();const start=new Date(nowD.getFullYear(),nowD.getMonth()-months+1,1);const prevStart=new Date(start.getFullYear(),start.getMonth()-months,1);const current=paid.filter(p=>localDate(p.paidAt!)>=start).reduce((s,p)=>s+p.amount,0);const previous=paid.filter(p=>localDate(p.paidAt!)>=prevStart&&localDate(p.paidAt!)<start).reduce((s,p)=>s+p.amount,0);const delta=previous?((current-previous)/previous)*100:null;
 const buckets=Array.from({length:months},(_,i)=>{const d=new Date(start.getFullYear(),start.getMonth()+i,1);const next=new Date(d.getFullYear(),d.getMonth()+1,1);return {label:new Intl.DateTimeFormat('it-IT',{month:'short'}).format(d),value:paid.filter(p=>localDate(p.paidAt!)>=d&&localDate(p.paidAt!)<next).reduce((s,p)=>s+p.amount,0)}});const prevBuckets=Array.from({length:months},(_,i)=>{const d=new Date(prevStart.getFullYear(),prevStart.getMonth()+i,1);const next=new Date(d.getFullYear(),d.getMonth()+1,1);return {value:paid.filter(p=>localDate(p.paidAt!)>=d&&localDate(p.paidAt!)<next).reduce((s,p)=>s+p.amount,0)}});const max=Math.max(1,...buckets.map(b=>b.value),...prevBuckets.map(b=>b.value));const makePoints=(arr:{value:number}[])=>arr.length===1?`0,${90-(arr[0].value/max)*75} 100,${90-(arr[0].value/max)*75}`:arr.map((b,i)=>`${(i/(arr.length-1))*100},${90-(b.value/max)*75}`).join(' ');const byClient=clients.filter(c=>!c.deletedAt).map(c=>({c,value:paid.filter(p=>p.clientId===c.id).reduce((s,p)=>s+p.amount,0)})).sort((a,b)=>b.value-a.value);
 return <main className="page"><header className="page-title"><div><h1>Entrate</h1><p>Incassi, scadenze e andamento in un colpo d’occhio.</p></div><PrimaryButton onClick={()=>setAdd(true)}>+ Pagamento</PrimaryButton></header>
 <div className="stats-grid"><Card><span>Entrate totali</span><strong>€ {totalPaid.toLocaleString('it-IT')}</strong></Card><Card><span>Periodo corrente</span><strong>€ {current.toLocaleString('it-IT')}</strong><small>{delta===null?'Nessun confronto disponibile':`${delta>=0?'+':''}${delta.toFixed(0)}% vs periodo precedente`}</small></Card><Card><span>Da ricevere</span><strong>€ {totalPending.toLocaleString('it-IT')}</strong><small>{pending.length} pagamenti</small></Card></div>
 <Card className="revenue-chart"><div className="section-head compact"><div><h2>Andamento entrate</h2><p>Il tratto più tenue mostra il periodo precedente.</p></div><div className="chips">{([1,3,6,12] as const).map(n=><Chip active={months===n} onClick={()=>setMonths(n)} key={n}>{n===12?'1 anno':`${n} ${n===1?'mese':'mesi'}`}</Chip>)}</div></div><div className="chart-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Grafico entrate"><polyline className="previous-line" points={makePoints(prevBuckets)}/><polyline className="current-line" points={makePoints(buckets)}/></svg><div className="chart-labels">{buckets.map((b,i)=><span key={i}>{b.label}<b>€{Math.round(b.value)}</b></span>)}</div></div></Card>
 <div className="bento"><Card className="span2"><span className="eyebrow">PAGAMENTI</span>{active.sort((a,b)=>+localDate(b.dueDate)-+localDate(a.dueDate)).map(p=>{const c=clients.find(x=>x.id===p.clientId);return <div className="payment-row" key={p.id}><div><strong>{c?.name||'Cliente'}</strong><span>€ {p.amount.toLocaleString('it-IT')} · scad. {fmtDate(p.dueDate)}</span></div><button className={`status ${paymentStatus(p).toLowerCase().replace(' ','-')}`} onClick={()=>{db.payments.update(p.id,{paidAt:p.paidAt?undefined:now(),updatedAt:now()});queueSync()}}>{paymentStatus(p)}</button></div>})}</Card><Card><span className="eyebrow">PER CLIENTE</span>{byClient.map(x=><div className="line" key={x.c.id}><span>{x.c.name}</span><strong>€ {x.value.toLocaleString('it-IT')}</strong></div>)}</Card></div>
 {add&&<PaymentForm close={()=>setAdd(false)}/>}</main>;
}
