import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { db, now } from '../lib/db';
import { verifyPin, makePinHash } from '../lib/security';
import { exportAll, getSyncCode, importAll, queueSync, resetRemote, setSyncCode } from '../services/sync';
import { downloadText } from '../lib/exportScript';
import { Card, PrimaryButton } from '../components/UI';
import { Modal } from '../components/Forms';

export function SettingsPage(){
 const settings=useLiveQuery(()=>db.settings.get('settings'),[]);const [syncCode,setSyncCodeState]=useState('');const [newSyncCode,setNewSyncCode]=useState('');const [syncMessage,setSyncMessage]=useState('');const [resetOpen,setResetOpen]=useState(false);
 useEffect(()=>{getSyncCode().then(setSyncCodeState)},[]);
 const fileRef=async()=>{const p=await exportAll();downloadText(`marketero-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(p,null,2),'application/json')};
 async function copySyncCode(){const code=await getSyncCode();await navigator.clipboard.writeText(code);setSyncMessage('Codice copiato ✓')}
 async function connectDevice(){if(!newSyncCode.trim()){setSyncMessage('Inserisci il codice del dispositivo principale.');return}const old=await getSyncCode();try{const code=newSyncCode.trim().toLowerCase();await setSyncCode(code);setSyncCodeState(code);setNewSyncCode('');setSyncMessage('Dispositivo collegato. La sincronizzazione è automatica ✓');queueSync()}catch(error:any){await setSyncCode(old).catch(()=>{});setSyncMessage('Errore: '+(error?.message||'Impossibile collegare il dispositivo'))}}
 return <main className="page"><header className="page-title"><div><h1>Impostazioni</h1><p>Solo controlli utili per app, sicurezza e dati.</p></div></header><div className="settings-grid">
 <Card><h3>App</h3><label className="setting-field">Nome<input value={settings?.userName||''} placeholder="Il tuo nome" onChange={e=>settings&&db.settings.update('settings',{userName:e.target.value,updatedAt:now()})} onBlur={queueSync}/></label><button className="btn ghost" onClick={()=>settings&&db.settings.update('settings',{darkMode:!settings.darkMode,updatedAt:now()}).then(()=>queueSync())}>{settings?.darkMode?'Usa tema chiaro':'Usa tema scuro'}</button></Card>
 <Card><h3>Sicurezza</h3><p className="muted">PIN sincronizzato tra i dispositivi collegati. Il codice di recupero non viene mostrato nell’app.</p><ChangePin/></Card>
 <Card><h3>Notifiche</h3>{[['notificationsEnabled','Notifiche'],['notificationDeadlines','Scadenze clienti'],['notificationAppointments','Appuntamenti'],['notificationReminders','Reminder']].map(([k,l])=><label className="toggle-row" key={k}><span>{l}</span><input type="checkbox" checked={Boolean((settings as any)?.[k])} onChange={e=>settings&&db.settings.update('settings',{[k]:e.target.checked,updatedAt:now()}).then(()=>queueSync())}/></label>)}</Card>
 <Card><h3>Dati e sincronizzazione</h3><p className="muted">Stato: sincronizzazione automatica attiva.</p><p className="muted">Ultimo aggiornamento: {settings?.lastSyncAt?new Date(settings.lastSyncAt).toLocaleString('it-IT'):'in attesa'}</p><label className="setting-field">Codice dispositivo<input readOnly value={syncCode}/></label><button className="btn ghost" onClick={copySyncCode}>Copia codice</button><label className="setting-field">Collega questo dispositivo<input value={newSyncCode} onChange={e=>setNewSyncCode(e.target.value)} placeholder="Incolla codice"/></label><PrimaryButton onClick={connectDevice}>Collega</PrimaryButton>{syncMessage&&<p className="muted">{syncMessage}</p>}<div className="data-actions"><button className="btn ghost" onClick={fileRef}>Esporta dati</button><label className="file-btn">Importa dati<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f){await importAll(JSON.parse(await f.text()));queueSync();location.reload()}}}/></label></div></Card>
 <Link className="settings-link" to="/pagamenti"><Card><h3>Entrate e pagamenti</h3><p>Apri il riepilogo economico e il grafico.</p><strong>Apri →</strong></Card></Link>
 <Card className="danger-zone"><h3>Zona critica</h3><p className="muted">Elimina i dati locali e sincronizzati solo dopo doppia conferma.</p><button className="btn danger" onClick={()=>setResetOpen(true)}>Resetta tutti i dati</button></Card>
 </div>{resetOpen&&<ResetData close={()=>setResetOpen(false)}/>}</main>;
}
function ChangePin(){const settings=useLiveQuery(()=>db.settings.get('settings'),[]);const [open,setOpen]=useState(false);const [oldPin,setOldPin]=useState('');const [newPin,setNewPin]=useState('');const [msg,setMsg]=useState('');async function save(){if(!(await verifyPin(oldPin,settings?.pinHash))){setMsg('PIN attuale non corretto.');return}if(newPin.length!==4){setMsg('Il nuovo PIN deve avere 4 cifre.');return}await db.settings.update('settings',{pinHash:await makePinHash(newPin),updatedAt:now()});queueSync();setMsg('PIN aggiornato ✓');setOldPin('');setNewPin('')}return <>{!open?<button className="btn ghost" onClick={()=>setOpen(true)}>Cambia PIN</button>:<div className="mini-form"><input inputMode="numeric" maxLength={4} placeholder="PIN attuale" value={oldPin} onChange={e=>setOldPin(e.target.value.replace(/\D/g,''))}/><input inputMode="numeric" maxLength={4} placeholder="Nuovo PIN" value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,''))}/><PrimaryButton onClick={save}>Salva PIN</PrimaryButton>{msg&&<small>{msg}</small>}</div>}</>}
function ResetData({close}:{close:()=>void}){const settings=useLiveQuery(()=>db.settings.get('settings'),[]);const [pin,setPin]=useState('');const [phrase,setPhrase]=useState('');const [msg,setMsg]=useState('');async function run(){if(!(await verifyPin(pin,settings?.pinHash))){setMsg('PIN non corretto.');return}if(phrase!=='RESETTA'){setMsg('Scrivi RESETTA per confermare.');return}try{await resetRemote();await db.delete();location.reload()}catch(e:any){setMsg(e?.message||'Reset non riuscito')}}return <Modal title="Resetta tutti i dati" close={close}><div className="form"><p>Questa azione elimina i dati dell’app anche dal cloud sincronizzato.</p><label>PIN<input inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><label>Scrivi RESETTA<input value={phrase} onChange={e=>setPhrase(e.target.value)}/></label>{msg&&<p className="error">{msg}</p>}<button className="btn danger" onClick={run}>Conferma eliminazione definitiva</button></div></Modal>}
