import { useEffect, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Trash2 } from 'lucide-react';
import { db, now, uid } from '../lib/db';
import { dateOnly, getConflicts } from '../lib/logic';
import { inputDate, WORKFLOW } from '../lib/ui';
import { queueSync } from '../services/sync';
import { Chip, PrimaryButton } from './UI';
import type { CalendarEvent, Client, ContentFormat, Idea, Lead, Platform, WorkflowStage } from '../types/models';

export function Modal({title,close,children}:{title:string;close:()=>void;children:any}){return <div className="sheet-backdrop" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><div className="sheet-head"><h2>{title}</h2><button className="icon" onClick={close}>✕</button></div><div className="modal-scroll">{children}</div></div></div>;}
export function FieldChips({title,values,value,setValue}:{title:string;values:string[];value:string;setValue:(v:any)=>void}){return <fieldset><legend>{title}</legend><div className="chips">{values.map(v=><Chip key={v} active={value===v} onClick={()=>setValue(v)}>{v}</Chip>)}</div></fieldset>;}

export function IdeaForm({close}:{close:()=>void}){
 const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const [title,setTitle]=useState('');const [clientId,setClientId]=useState('');const [platform,setPlatform]=useState<Platform>('Instagram');const [format,setFormat]=useState<ContentFormat>('Reel');const [url,setUrl]=useState('');
 async function save(e:any){e.preventDefault();const t=now();await db.ideas.put({id:uid(),title,clientId:clientId||undefined,platform,format,referenceUrls:url?[{url}]:[],status:'Idea',createdAt:t,updatedAt:t});queueSync();close()}
 return <Modal title="Nuova idea" close={close}><form onSubmit={save} className="form"><label>Titolo<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Cliente<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Nessuno</option>{clients.filter(c=>!c.deletedAt).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><FieldChips title="Piattaforma" values={['Instagram','TikTok','Entrambi']} value={platform} setValue={setPlatform}/><FieldChips title="Formato" values={['Reel','TikTok Video','Post','Carousel','Story']} value={format} setValue={setFormat}/><label>URL riferimento<input type="url" placeholder="https://..." value={url} onChange={e=>setUrl(e.target.value)}/></label><PrimaryButton type="submit">Salva idea</PrimaryButton></form></Modal>;
}

export function ClientForm({close,after}:{close:()=>void;after:(id:string)=>void}){
 const [step,setStep]=useState(1);const [v,setV]=useState({name:'',niche:'Ristorante',description:'',instagram:'',tiktok:'',monthlyFee:'',contentTarget:'10',metaAds:false,objective:'',tone:'Diretto e professionale',startDate:inputDate()});
 async function save(){const id=uid(),t=now();await db.clients.put({id,name:v.name,niche:v.niche,description:v.description,instagram:v.instagram,tiktok:v.tiktok,monthlyFee:Number(v.monthlyFee.replace(',','.')||0),contentTarget:Number(v.contentTarget||0),startDate:v.startDate,metaAds:v.metaAds,objective:v.objective,tone:v.tone,avoid:[],platforms:[...(v.instagram?['Instagram' as Platform]:[]),...(v.tiktok?['TikTok' as Platform]:[])],createdAt:t,updatedAt:t});queueSync();close();after(id)}
 return <Modal title={`Nuovo cliente · ${step}/4`} close={close}><div className="progress"><span style={{width:`${step*25}%`}}/></div><div className="form">{step===1&&<><label>Nome<input required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Data inizio collaborazione<input required type="date" value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/></label><label>Nicchia<select value={v.niche} onChange={e=>setV({...v,niche:e.target.value})}>{['Ristorante','Abbigliamento','Concessionaria','Beauty','Fitness','Immobiliare','Hospitality','Retail','Professionista','Dentista','Bar','Formazione','Servizi','E-commerce','Altro'].map(x=><option key={x}>{x}</option>)}</select></label><label>Descrizione<textarea value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label></>}{step===2&&<><label>Instagram<input value={v.instagram} onChange={e=>setV({...v,instagram:e.target.value})}/></label><label>TikTok<input value={v.tiktok} onChange={e=>setV({...v,tiktok:e.target.value})}/></label></>}{step===3&&<><label>Compenso mensile<input inputMode="decimal" placeholder="0" value={v.monthlyFee} onChange={e=>setV({...v,monthlyFee:e.target.value.replace(/[^0-9.,]/g,'')})}/></label><label className="check"><input type="checkbox" checked={v.metaAds} onChange={e=>setV({...v,metaAds:e.target.checked})}/> Meta Ads</label></>}{step===4&&<><label>Target contenuti/mese<input inputMode="numeric" placeholder="0" value={v.contentTarget} onChange={e=>setV({...v,contentTarget:e.target.value.replace(/\D/g,'')})}/></label><label>Obiettivo<input value={v.objective} onChange={e=>setV({...v,objective:e.target.value})}/></label><label>Tono di voce<input value={v.tone} onChange={e=>setV({...v,tone:e.target.value})}/></label></>}<div className="row spread sticky-actions">{step>1?<button className="btn ghost" onClick={()=>setStep(step-1)}>Indietro</button>:<span/>}{step<4?<PrimaryButton onClick={()=>setStep(step+1)}>Continua</PrimaryButton>:<PrimaryButton disabled={!v.name||!v.startDate} onClick={save}>Crea cliente</PrimaryButton>}</div></div></Modal>;
}

export function ScriptForm({client,ideas=[],close}:{client?:Client;ideas?:Idea[];close:()=>void}){
 const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const [clientId,setClientId]=useState(client?.id||'');const queriedIdeas=useLiveQuery(()=>clientId?db.ideas.where('clientId').equals(clientId).toArray():[],[clientId])||[];const linkedIdeas=client?ideas:queriedIdeas;
 const [v,setV]=useState({title:'',ideaId:'',platform:'Instagram' as Platform,format:'Reel' as ContentFormat,status:'Da scrivere' as const,hook:'',body:'',cta:'',recordingNotes:'',url:''});
 useEffect(()=>{const i=linkedIdeas.find(x=>x.id===v.ideaId);if(i)setV(o=>({...o,title:i.title,platform:i.platform,format:i.format,url:i.referenceUrls[0]?.url||''}))},[v.ideaId]);
 async function save(e:any){e.preventDefault();if(!clientId)return;const t=now();await db.scripts.put({id:uid(),clientId,ideaId:v.ideaId||undefined,title:v.title,platform:v.platform,format:v.format,status:v.status,hook:v.hook,body:v.body,cta:v.cta,recordingNotes:v.recordingNotes,referenceUrls:v.url?[{url:v.url}]:[],createdAt:t,updatedAt:t});queueSync();close()}
 return <Modal title="Nuovo script" close={close}><form className="form" onSubmit={save}>{!client&&<label>Cliente<select required value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Seleziona cliente</option>{clients.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>Da idea esistente<select value={v.ideaId} onChange={e=>setV({...v,ideaId:e.target.value})}><option value="">Nessuna</option>{linkedIdeas.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><label>Titolo<input required value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><FieldChips title="Piattaforma" values={['Instagram','TikTok','Entrambi']} value={v.platform} setValue={(x:any)=>setV({...v,platform:x})}/><FieldChips title="Formato" values={['Reel','TikTok Video','Post','Carousel','Story']} value={v.format} setValue={(x:any)=>setV({...v,format:x})}/><FieldChips title="Stato" values={['Da scrivere','In corso','Pronto']} value={v.status} setValue={(x:any)=>setV({...v,status:x})}/><label>Hook<textarea value={v.hook} onChange={e=>setV({...v,hook:e.target.value})}/></label><label>Testo<textarea rows={8} value={v.body} onChange={e=>setV({...v,body:e.target.value})}/></label><label>CTA<textarea value={v.cta} onChange={e=>setV({...v,cta:e.target.value})}/></label><label>Note registrazione<textarea value={v.recordingNotes} onChange={e=>setV({...v,recordingNotes:e.target.value})}/></label><label>URL riferimento<input type="url" value={v.url} onChange={e=>setV({...v,url:e.target.value})}/></label><PrimaryButton type="submit" disabled={!clientId}>Salva script</PrimaryButton></form></Modal>;
}

export function EventForm({kind,close,initial}:{kind:'Lavoro'|'Personale';close:()=>void;initial?:CalendarEvent}){
 const events=useLiveQuery(()=>db.events.toArray(),[])||[];const [title,setTitle]=useState(initial?.title||'');const [date,setDate]=useState(initial?dateOnly(initial.startAt):inputDate());const initialHasTime=initial?!initial.allDay:false;const [time,setTime]=useState(initialHasTime?new Date(initial!.startAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'');const [category,setCategory]=useState(initial?.category||(kind==='Personale'?'Personale':'Appuntamento'));
 async function save(e:any){e.preventDefault();const t=now();const startAt=time?new Date(`${date}T${time}:00`).toISOString():date;const candidate:CalendarEvent={id:initial?.id||uid(),title,kind,category,startAt,allDay:!time,createdAt:initial?.createdAt||t,updatedAt:t};const c=getConflicts(candidate,events);if(c.length&&!confirm(`Conflitto con: ${c.map(x=>x.kind==='Personale'?'Fascia occupata':x.title).join(', ')}. Inserire comunque?`))return;await db.events.put(candidate);queueSync();close()}
 async function remove(){if(!initial)return;if(confirm('Eliminare questo evento?')){await db.events.update(initial.id,{deletedAt:now(),updatedAt:now()});queueSync();close()}}
 return <Modal title={initial?'Modifica evento':kind==='Personale'?'Nuovo impegno personale':'Nuovo appuntamento lavoro'} close={close}><form className="form" onSubmit={save}><label>Titolo<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Data<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ora <small>(opzionale)</small><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}>{(kind==='Personale'?['Personale','Famiglia','Salute','Sport','Commissione']:['Appuntamento','Registrazione','Montaggio','Programmazione','Pubblicazione']).map(x=><option key={x}>{x}</option>)}</select></label><div className="row spread"><PrimaryButton type="submit">Salva</PrimaryButton>{initial&&<button type="button" className="btn danger subtle" onClick={remove}><Trash2 size={16}/> Elimina</button>}</div></form></Modal>;
}

export function TaskForm({close,clientId,defaultStage}:{close:()=>void;clientId?:string;defaultStage?:WorkflowStage}){
 const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const [title,setTitle]=useState('');const [duration,setDuration]=useState('45');const [date,setDate]=useState(inputDate());const [time,setTime]=useState('');const [cid,setCid]=useState(clientId||'');const [stage,setStage]=useState<WorkflowStage|''>(defaultStage||'');
 async function save(e:any){e.preventDefault();const t=now();const dueAt=time?new Date(`${date}T${time}:00`).toISOString():date;await db.tasks.put({id:uid(),title,durationMin:Number(duration||0),urgent:false,completed:false,clientId:cid||undefined,stage:stage||undefined,dueAt,createdAt:t,updatedAt:t});queueSync();close()}
 return <Modal title="Nuova attività" close={close}><form className="form" onSubmit={save}><label>Titolo<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Data<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ora <small>(opzionale)</small><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Durata (min)<input inputMode="numeric" placeholder="0" value={duration} onChange={e=>setDuration(e.target.value.replace(/\D/g,''))}/></label>{!clientId&&<label>Cliente <small>(opzionale)</small><select value={cid} onChange={e=>setCid(e.target.value)}><option value="">Nessuno</option>{clients.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>Fase <small>(opzionale)</small><select value={stage} onChange={e=>setStage(e.target.value as WorkflowStage|'')}><option value="">Nessuna</option>{WORKFLOW.map(x=><option key={x}>{x}</option>)}</select></label><PrimaryButton type="submit">Salva attività</PrimaryButton></form></Modal>;
}

export function LeadForm({close}:{close:()=>void}){const [name,setName]=useState('');const [contact,setContact]=useState('');const [value,setValue]=useState('');const [status,setStatus]=useState<Lead['status']>('Da contattare');async function save(e:any){e.preventDefault();const t=now();await db.leads.put({id:uid(),name,contact,monthlyValue:Number(value.replace(',','.')||0),status,createdAt:t,updatedAt:t});queueSync();close()}return <Modal title="Nuovo lead" close={close}><form className="form" onSubmit={save}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Contatto<input value={contact} onChange={e=>setContact(e.target.value)}/></label><label>Valore mensile<input inputMode="decimal" placeholder="0" value={value} onChange={e=>setValue(e.target.value.replace(/[^0-9.,]/g,''))}/></label><label>Stato<select value={status} onChange={e=>setStatus(e.target.value as Lead['status'])}>{['Da contattare','Contattato','Appuntamento','Proposta inviata','Acquisito','Perso'].map(x=><option key={x}>{x}</option>)}</select></label><PrimaryButton type="submit">Salva lead</PrimaryButton></form></Modal>;}

export function PaymentForm({close}:{close:()=>void}){const clients=useLiveQuery(()=>db.clients.toArray(),[])||[];const [clientId,setClientId]=useState('');const [amount,setAmount]=useState('');const [dueDate,setDueDate]=useState(inputDate());const [paid,setPaid]=useState(false);async function save(e:any){e.preventDefault();const t=now();await db.payments.put({id:uid(),clientId,amount:Number(amount.replace(',','.')||0),dueDate,paidAt:paid?t:undefined,createdAt:t,updatedAt:t});queueSync();close()}return <Modal title="Nuovo pagamento" close={close}><form className="form" onSubmit={save}><label>Cliente<select required value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Seleziona cliente</option>{clients.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Importo<input inputMode="decimal" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.,]/g,''))}/></label><label>Scadenza<input type="date" required value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label className="check"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/> Già incassato</label><PrimaryButton type="submit" disabled={!clientId}>Salva pagamento</PrimaryButton></form></Modal>;}
